/**
 *
 * $Id$
 */
package smart_nursing_home.validation;

import org.eclipse.emf.common.util.EList;

import smart_nursing_home.Medicine;
import smart_nursing_home.Room;

/**
 * A sample validator interface for {@link smart_nursing_home.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateMedicine(EList<Medicine> value);

	boolean validateRoom(Room value);
}
