/**
 *
 * $Id$
 */
package smart_nursing_home.validation;

import org.eclipse.emf.common.util.EList;

import smart_nursing_home.Brightness;
import smart_nursing_home.Cleanness;
import smart_nursing_home.Door;
import smart_nursing_home.Heater;
import smart_nursing_home.Humidifier;
import smart_nursing_home.Humidity;
import smart_nursing_home.Light;
import smart_nursing_home.Person;
import smart_nursing_home.Roomba;
import smart_nursing_home.Temperature;
import smart_nursing_home.Window;

/**
 * A sample validator interface for {@link smart_nursing_home.Room}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoomValidator {
	boolean validate();

	boolean validateWindow(Window value);
	boolean validateLight(Light value);
	boolean validateHumidifier(Humidifier value);
	boolean validateHeater(Heater value);
	boolean validateBrightness(Brightness value);
	boolean validateHumidity(Humidity value);
	boolean validateTemperature(Temperature value);
	boolean validateDoor(EList<Door> value);
	boolean validatePerson(EList<Person> value);

	boolean validateRoomba(EList<Roomba> value);

	boolean validateCleanness(Cleanness value);
}
