/**
 *
 * $Id$
 */
package smart_office.validation;

import org.eclipse.emf.common.util.EList;

import smart_office.Clazz;

/**
 * A sample validator interface for {@link smart_office.SmartOffice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SmartOfficeValidator {
	boolean validate();

	boolean validateClazz(EList<Clazz> value);
}
